services:
  - type: web
    name: ai-trading-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # Check if node is available, if not install it
      if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      fi
      # Build Angular app
      cd frontend && npm install && npm run build
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PAPER
        value: "True"
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
    healthCheckPath: /api/status