services:
  - type: web
    name: ai-trading-bot
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      cd frontend && npm install && npm run build
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PAPER
        value: "True"
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
    healthCheckPath: /api/status