services:
  - type: web
    name: ai-trading-bot
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PAPER
        value: "True"
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
    healthCheckPath: /api/status